repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.3.0
    hooks:
    -   id: check-yaml
    -   id: end-of-file-fixer
    -   id: trailing-whitespace
    -   id: name-tests-test
    -   id: detect-aws-credentials
        args:
        - --allow-missing-credentials


-   repo: https://github.com/psf/black
    rev: 22.10.0
    hooks:
    -   id: black

-   repo: https://github.com/gitleaks/gitleaks
    rev: v8.16.1
    hooks:
    -   id: gitleaks

-   repo: https://github.com/antonbabenko/pre-commit-terraform
    rev: v1.83.5
    hooks:
    -   id: terraform_fmt

-   repo: https://github.com/Lucas-C/pre-commit-hooks
    rev: v1.5.4
    hooks:
    -   id: forbid-crlf
    -   id: remove-crlf

-   repo: https://github.com/terraform-docs/terraform-docs
    rev: v0.16.0
    hooks:
    -    id: terraform-docs-go
         args: ["markdown", "table", "--output-file", "README.md", "./mymodule"]
